### ISSUE TITLE
load_eplet_registry() error

### ISSUE THREAD

**Issue by D-Sierra** [lcreteig/hlapro#8]
Hi,

I encounter an error when using load_eplet_registry() function for the first time. After being asked whether I want to download the HLA Eplet Registry tables and pressing "1" to continue with the download the following error occurs:

```
Error in `purrr::map()`:                                                                            
ℹ In index: 1.
Caused by error in `recycle_columns()`:
! Tibble columns must have compatible sizes.
• Size 0: Column `alleles_all`.
• Size 252: Columns `id`, `name`, `description`, `exposition`, `confirmation`, and 1 more.
ℹ Only values of size one are recycled.
Run `rlang::last_trace()` to see where the error occurred.
```

Running rlang:last_trace() I obtain the following report:

```
Backtrace:
     ▆
  1. └─hlapro::load_eplet_registry()
  2.   └─hlapro:::scrape_eplet_registry(file_path)
  3.     ├─dplyr::mutate(...)
  4.     ├─dplyr::ungroup(...)
  5.     ├─dplyr::filter(...)
  6.     ├─tidyr::separate_longer_delim(...)
  7.     │ └─tidyr:::check_data_frame(data)
  8.     │   └─base::is.data.frame(x)
  9.     ├─dplyr::group_by(...)
 10.     ├─tidyr::pivot_longer(...)
 11.     ├─dplyr::mutate(...)
 12.     ├─purrr::list_rbind(...)
 13.     │ └─purrr:::check_list_of_data_frames(x)
 14.     │   └─vctrs::vec_check_list(x, call = error_call)
 15.     │     └─vctrs::obj_check_list(x, ..., arg = arg, call = call)
 16.     └─purrr::map(...)
 17.       └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
 18.         ├─purrr:::with_indexed_errors(...)
 19.         │ └─base::withCallingHandlers(...)
 20.         ├─purrr:::call_with_cleanup(...)
 21.         ├─tibble (local) .f(.x[[i]], ...)
 22.         └─tibble:::as_tibble.list(.x[[i]], ...)
 23.           └─tibble:::lst_to_tibble(x, .rows, .name_repair, col_lengths(x))
 24.             └─tibble:::recycle_columns(x, .rows, lengths)
 ```

I'm working with R version 4.3.2, purrr 1.0.2 and tibble 3.2.1.

Any help to overcome this issue will be welcomed,

-Dani

**Comment by lcreteig** [comment]
Hi Dani,

Thanks for trying out the package, and for reporting this. I just tried it on my machine and can reproduce your error. 

I see that the [HLA eplet registry website](https://www.epregistry.com.br) has been updated last week. I'm not sure what it is yet, but I presume that the structure of the website has changed in that update, so I'll have to change the scraping code as well.

I'll try to look into this in the next few days and push a fix; I'll let you know if and when I do.

-Leon

**Comment by lcreteig** [comment]
I should have addressed this now. There were quite a few changes apparently in the latest update of the registry; see the commits in #9 for more details.

I just pushed a (long overdue) new release with the current state of the package.

```r
remotes::install_github("lcreteig/hlapro@v.2.0")
# or just to get the latest version (currently v.2.0)
remotes::install_github("lcreteig/hlapro")
```

I didn't think anybody else was using it to be honest, but I hope it's useful for you 😇

**Comment by D-Sierra** [comment]
Nice! I will test it as soon as I can.

Thank you for the library and for all your help!
